name=HDSP2112
version=1.0.0
author=Your Name
maintainer=Your Name <email@example.com>
sentence=Library for HDSP2112 LCD display control.
paragraph=Simple library for HDSP2112 LCD display using 74HC164D.
category=Display
url=https://github.com/yourusername/HDSP2112
architectures=*
